** DONE:
Maybe you can add a middle ground parents with position relative?

Something like a div in between the parent component and the image component

** TODO:
Consider renaming this main-content or something else along those lines,
Having a class named main and an HTML element named main here can sometimes trip us up.
you can also just select the main HTML item here if that's what you're going for.
If that doesn't work, you can add this main class CSS into the
containing object using the main -element selector.

* TODO:
holding these images in the state since they will be fetched and the page has to re-render to show these changes.
Since you're creating this image bit 3 times, I'd go as far as saying this should be its own iterable component.
When data is coming into the website we're going to have more than 4 bits of cover art so I'd suggest updating this in a way that allows for more flexibility.

* TODO:
This would break/error in the case that there were only one image to display as well.
We would also like to dynamically set the alt text of the cover image to be something like

* TODO:
alt={${album_song} cover art}
Rather than creating 4 different image classes here you can do something like this using nth item

* TODO:
.myClass img:nth-child(1) { animation-delay: .5s }
.myClass img:nth-child(2) { animation-delay: 1s }
.myClass img:nth-child(3) { animation-delay: 1.5s }
.myClass img:nth-child(4) { animation-delay: 2s }
or use the @for ability inside of scss like this ->

@for $i from 1 through 3 {
  ul:nth-child(3n + #{$i}) {
    background-color: lighten($base-color, $i * 5%);
  }
}

