* TODO: hook up back end

** TODO: display images from top tracks alt={${album_song} cover art} 
** TODO:look up component did mount and where it'll pull data if not signed in 
** TODO:display images from playlists 

* DONE:
holding these images in the state since they will be fetched and the page has to re-render to show these changes.
Since you're creating this image bit 3 times, I'd go as far as saying this should be its own iterable component.
When data is coming into the website we're going to have more than 4 bits of cover art
 so I'd suggest updating this in a way that allows for more flexibility.

* DONE:
This would break/error in the case that there were only one image to display as well.
We would also like to dynamically set the alt text of the cover image to be something like


* DONE:
.myClass img:nth-child(1) { animation-delay: .5s }
.myClass img:nth-child(2) { animation-delay: 1s }
.myClass img:nth-child(3) { animation-delay: 1.5s }
.myClass img:nth-child(4) { animation-delay: 2s }
or use the @for ability inside of scss like this ->

@for $i from 1 through 3 {
  ul:nth-child(3n + #{$i}) {
    background-color: lighten($base-color, $i * 5%);
  }
}

